variable "region_name" {}
variable "vpc_cidr_block" {}
variable "vpc_tags" {}
#variable "sub_cidr_block" {}
variable "sub_az" {}
#variable "sub_tags" {}
variable "igw_tags" {}
variable "rt_cidr_block" {}
variable "rt_tags" {}
variable "ec2_az" {}
variable "ec2_inst_type" {}
variable "ec2_key_name" {}
variable "env" {}
variable "public_subnet1_name" {}
variable "public_subnet2_name" {}
variable "public_subnet3_name" {}
variable "public_subnet1_cidr" {}
variable "public_subnet2_cidr" {}
variable "public_subnet3_cidr" {}
